export const breadcrumbLabels: Record<string, { ar: string; en: string }> = {
  '/': { ar: 'بوابة الدخول', en: 'Gateway' },
  '/ar/': { ar: 'الرئيسية', en: 'Home' },
  '/ar/about/': { ar: 'نبذة', en: 'About' },
  '/ar/cv/': { ar: 'السيرة الذاتية', en: 'CV' },
  '/ar/books/': { ar: 'الكتب', en: 'Books' },
  '/ar/editions/': { ar: 'التحقيقات', en: 'Critical Editions' },
  '/ar/articles/': { ar: 'المقالات', en: 'Articles' },
  '/ar/fields/': { ar: 'المجالات العلمية', en: 'Scholarly Fields' },
  '/ar/projects/': { ar: 'المشروعات', en: 'Projects' },
  '/ar/media/': { ar: 'الوسائط', en: 'Media' },
  '/ar/external-links/': { ar: 'الروابط الخارجية', en: 'External Links' },
  '/ar/contact/': { ar: 'تواصل', en: 'Contact' },
  '/ar/learning-path/': { ar: 'المسار التعليمي', en: 'Learning Path' },
  '/ar/site-map/': { ar: 'دليل الموقع', en: 'Site Index' },
  '/ar/fields/islamic-studies/': { ar: 'الدراسات الإسلامية', en: 'Islamic Studies' },
  '/ar/fields/defense-of-sunnah/': { ar: 'الدفاع عن السنة والشبهات', en: 'Defense of Sunnah' },
  '/ar/fields/alukah/': { ar: 'الألوكة', en: 'Alukah' },
  '/ar/fields/alukah/articles/': { ar: 'مقالات الألوكة', en: 'Alukah Articles' },
  '/ar/fields/manuscripts/': { ar: 'المخطوطات', en: 'Manuscripts' },
  '/ar/fields/ai-and-islamic-heritage/': { ar: 'الذكاء الاصطناعي والتراث الإسلامي', en: 'AI and Islamic Heritage' },
  '/ar/fields/academic-reviewing/': { ar: 'التحكيم العلمي', en: 'Academic Reviewing' },
  '/ar/fields/e-learning/': { ar: 'التعليم الإلكتروني للعلوم الإسلامية', en: 'E-Learning in Islamic Studies' },
  '/en/': { ar: 'الرئيسية', en: 'Home' },
  '/en/about/': { ar: 'نبذة', en: 'About' },
  '/en/cv/': { ar: 'السيرة الذاتية', en: 'CV' },
  '/en/books/': { ar: 'الكتب', en: 'Books' },
  '/en/critical-editions/': { ar: 'التحقيقات', en: 'Critical Editions' },
  '/en/articles/': { ar: 'المقالات', en: 'Articles' },
  '/en/scholarly-fields/': { ar: 'المجالات العلمية', en: 'Scholarly Fields' },
  '/en/projects/': { ar: 'المشروعات', en: 'Projects' },
  '/en/media/': { ar: 'الوسائط', en: 'Media' },
  '/en/external-links/': { ar: 'الروابط الخارجية', en: 'External Links' },
  '/en/contact/': { ar: 'تواصل', en: 'Contact' },
  '/en/learning-path/': { ar: 'المسار التعليمي', en: 'Learning Path' },
  '/en/site-map/': { ar: 'دليل الموقع', en: 'Site Index' },
  '/en/scholarly-fields/islamic-studies/': { ar: 'الدراسات الإسلامية', en: 'Islamic Studies' },
  '/en/scholarly-fields/defense-of-sunnah/': { ar: 'الدفاع عن السنة والشبهات', en: 'Defense of Sunnah' },
  '/en/scholarly-fields/alukah/': { ar: 'الألوكة', en: 'Alukah' },
  '/en/scholarly-fields/alukah/articles/': { ar: 'مقالات الألوكة', en: 'Alukah Articles' },
  '/en/scholarly-fields/manuscripts/': { ar: 'المخطوطات', en: 'Manuscripts' },
  '/en/scholarly-fields/ai-and-islamic-heritage/': { ar: 'الذكاء الاصطناعي والتراث الإسلامي', en: 'AI and Islamic Heritage' },
  '/en/scholarly-fields/academic-reviewing/': { ar: 'التحكيم العلمي', en: 'Academic Reviewing' },
  '/en/scholarly-fields/e-learning/': { ar: 'التعليم الإلكتروني للعلوم الإسلامية', en: 'E-Learning in Islamic Studies' },
};
