export const breadcrumbLabels: Record<string, { ar: string; en: string }> = {
  '/': { ar: 'بوابة الدخول', en: 'Gateway' },
  '/ar/': { ar: 'الرئيسية', en: 'Home' },
  '/ar/about/': { ar: 'نبذة', en: 'About' },
  '/ar/cv/': { ar: 'السيرة الذاتية', en: 'CV' },
  '/ar/books/': { ar: 'الكتب', en: 'Books' },
  '/ar/editions/': { ar: 'التحقيقات', en: 'Critical Editions' },
  '/ar/articles/': { ar: 'المقالات', en: 'Articles' },
  '/ar/fields/': { ar: 'المجالات العلمية', en: 'Scholarly Fields' },
  '/ar/study/': { ar: 'مذاكرة طالب العلم', en: 'Study Hub' },
  '/ar/study/benefits/': { ar: 'فوائد من كتب متنوعة', en: 'Benefits from Books' },
  '/ar/study/benefits/methodology-and-usul/': { ar: 'المنهج والأصول', en: 'Methodology and Usul' },
  '/ar/study/benefits/tafsir-and-ulum-al-quran/': { ar: 'التفسير وعلوم القرآن', en: "Tafsir and Qur'anic Sciences" },
  '/ar/study/benefits/language-and-methodology/': { ar: 'اللغة والمنهج', en: 'Language and Methodology' },
  '/ar/study/benefits/manhaj-and-refutation/': { ar: 'المنهج والرد على المخالف', en: 'Method and Refutation' },
  '/ar/study/benefits/aqidah-and-iman/': { ar: 'العقيدة والإيمان', en: 'Creed and Faith' },
  '/ar/study/benefits/tafsir-and-language/': { ar: 'التفسير واللغة', en: 'Tafsir and Language' },
  '/ar/study/benefits/usul-al-fiqh/': { ar: 'أصول الفقه', en: 'Usul al-Fiqh' },
  '/ar/study/benefits/fiqh/': { ar: 'الفقه', en: 'Fiqh' },
  '/ar/study/benefits/tazkiyah-and-adab/': { ar: 'التزكية وآداب الطلب', en: 'Tazkiyah and Study Adab' },
  '/ar/study/benefits/methodology-and-usul/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/ar/study/benefits/tafsir-and-ulum-al-quran/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/ar/study/benefits/tafsir-and-language/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/ar/study/benefits/aqidah-and-iman/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/ar/study/benefits/fiqh/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/ar/study/benefits/tazkiyah-and-adab/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/ar/study/benefits/language-and-methodology/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/language-and-methodology/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/manhaj-and-refutation/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/aqidah-and-iman/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/tafsir-and-language/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/usul-al-fiqh/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/tazkiyah-and-adab/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/manhaj-and-refutation/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/aqidah-and-iman/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/tafsir-and-language/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/usul-al-fiqh/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/usul-al-fiqh/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/fiqh/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/benefits/tazkiyah-and-adab/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/ar/study/flashcards/': { ar: 'بطاقات المذاكرة', en: 'Flashcards' },
  '/ar/projects/': { ar: 'المشروعات', en: 'Projects' },
  '/ar/media/': { ar: 'الوسائط', en: 'Media' },
  '/ar/external-links/': { ar: 'الروابط الخارجية', en: 'External Links' },
  '/ar/contact/': { ar: 'تواصل', en: 'Contact' },
  '/ar/learning-path/': { ar: 'المسار التعليمي', en: 'Learning Path' },
  '/ar/site-map/': { ar: 'دليل الموقع', en: 'Site Index' },
  '/ar/fields/islamic-studies/': { ar: 'الدراسات الإسلامية', en: 'Islamic Studies' },
  '/ar/fields/defense-of-sunnah/': { ar: 'الدفاع عن السنة والشبهات', en: 'Defense of Sunnah' },
  '/ar/fields/alukah/': { ar: 'الألوكة', en: 'Alukah' },
  '/ar/fields/alukah/articles/': { ar: 'مقالات الألوكة', en: 'Alukah Articles' },
  '/ar/fields/manuscripts/': { ar: 'المخطوطات', en: 'Manuscripts' },
  '/ar/fields/ai-and-islamic-heritage/': { ar: 'الذكاء الاصطناعي والتراث الإسلامي', en: 'AI and Islamic Heritage' },
  '/ar/fields/academic-reviewing/': { ar: 'التحكيم العلمي', en: 'Academic Reviewing' },
  '/ar/fields/e-learning/': { ar: 'التعليم الإلكتروني للعلوم الإسلامية', en: 'E-Learning in Islamic Studies' },
  '/en/': { ar: 'الرئيسية', en: 'Home' },
  '/en/about/': { ar: 'نبذة', en: 'About' },
  '/en/cv/': { ar: 'السيرة الذاتية', en: 'CV' },
  '/en/books/': { ar: 'الكتب', en: 'Books' },
  '/en/critical-editions/': { ar: 'التحقيقات', en: 'Critical Editions' },
  '/en/articles/': { ar: 'المقالات', en: 'Articles' },
  '/en/scholarly-fields/': { ar: 'المجالات العلمية', en: 'Scholarly Fields' },
  '/en/study/': { ar: 'مذاكرة طالب العلم', en: 'Study Hub' },
  '/en/study/benefits/': { ar: 'فوائد من كتب متنوعة', en: 'Benefits from Books' },
  '/en/study/benefits/methodology-and-usul/': { ar: 'المنهج والأصول', en: 'Methodology and Usul' },
  '/en/study/benefits/tafsir-and-ulum-al-quran/': { ar: 'التفسير وعلوم القرآن', en: "Tafsir and Qur'anic Sciences" },
  '/en/study/benefits/language-and-methodology/': { ar: 'اللغة والمنهج', en: 'Language and Methodology' },
  '/en/study/benefits/manhaj-and-refutation/': { ar: 'المنهج والرد على المخالف', en: 'Method and Refutation' },
  '/en/study/benefits/aqidah-and-iman/': { ar: 'العقيدة والإيمان', en: 'Creed and Faith' },
  '/en/study/benefits/tafsir-and-language/': { ar: 'التفسير واللغة', en: 'Tafsir and Language' },
  '/en/study/benefits/usul-al-fiqh/': { ar: 'أصول الفقه', en: 'Usul al-Fiqh' },
  '/en/study/benefits/fiqh/': { ar: 'الفقه', en: 'Fiqh' },
  '/en/study/benefits/tazkiyah-and-adab/': { ar: 'التزكية وآداب الطلب', en: 'Tazkiyah and Study Adab' },
  '/en/study/benefits/methodology-and-usul/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/en/study/benefits/tafsir-and-ulum-al-quran/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/en/study/benefits/tafsir-and-language/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/en/study/benefits/aqidah-and-iman/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/en/study/benefits/fiqh/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/en/study/benefits/tazkiyah-and-adab/tafsir-al-tabari-husayn-abd-al-raziq/': { ar: 'تفسير الطبري: الفاتحة والبقرة', en: "Tafsir al-Tabari: al-Fatihah and al-Baqarah" },
  '/en/study/benefits/language-and-methodology/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/language-and-methodology/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/manhaj-and-refutation/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/aqidah-and-iman/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/tafsir-and-language/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/usul-al-fiqh/al-risala-samy-al-arabi/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/tazkiyah-and-adab/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/manhaj-and-refutation/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/aqidah-and-iman/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/tafsir-and-language/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/usul-al-fiqh/al-risala-husayn-abd-al-raziq/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/usul-al-fiqh/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/fiqh/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/benefits/tazkiyah-and-adab/al-risala-ahmad-al-naqeeb/': { ar: 'الرسالة للشافعي', en: 'al-Risalah' },
  '/en/study/flashcards/': { ar: 'بطاقات المذاكرة', en: 'Flashcards' },
  '/en/projects/': { ar: 'المشروعات', en: 'Projects' },
  '/en/media/': { ar: 'الوسائط', en: 'Media' },
  '/en/external-links/': { ar: 'الروابط الخارجية', en: 'External Links' },
  '/en/contact/': { ar: 'تواصل', en: 'Contact' },
  '/en/learning-path/': { ar: 'المسار التعليمي', en: 'Learning Path' },
  '/en/site-map/': { ar: 'دليل الموقع', en: 'Site Index' },
  '/en/scholarly-fields/islamic-studies/': { ar: 'الدراسات الإسلامية', en: 'Islamic Studies' },
  '/en/scholarly-fields/defense-of-sunnah/': { ar: 'الدفاع عن السنة والشبهات', en: 'Defense of Sunnah' },
  '/en/scholarly-fields/alukah/': { ar: 'الألوكة', en: 'Alukah' },
  '/en/scholarly-fields/alukah/articles/': { ar: 'مقالات الألوكة', en: 'Alukah Articles' },
  '/en/scholarly-fields/manuscripts/': { ar: 'المخطوطات', en: 'Manuscripts' },
  '/en/scholarly-fields/ai-and-islamic-heritage/': { ar: 'الذكاء الاصطناعي والتراث الإسلامي', en: 'AI and Islamic Heritage' },
  '/en/scholarly-fields/academic-reviewing/': { ar: 'التحكيم العلمي', en: 'Academic Reviewing' },
  '/en/scholarly-fields/e-learning/': { ar: 'التعليم الإلكتروني للعلوم الإسلامية', en: 'E-Learning in Islamic Studies' },
};
